// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Clock {
    #[prost(map = "uint64, uint64", tag = "1")]
    pub values: ::std::collections::HashMap<u64, u64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClockInfo {
    #[prost(message, optional, tag = "1")]
    pub clock: ::core::option::Option<Clock>,
    /// id 为node id
    #[prost(bytes = "vec", tag = "2")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub message_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub count: u64,
    #[prost(uint64, tag = "5")]
    pub create_at: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MergeLog {
    #[prost(bytes = "vec", tag = "1")]
    pub from_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub start_count: u64,
    #[prost(uint64, tag = "4")]
    pub end_count: u64,
    #[prost(message, optional, tag = "5")]
    pub s_clock: ::core::option::Option<Clock>,
    #[prost(message, optional, tag = "6")]
    pub e_clock: ::core::option::Option<Clock>,
    #[prost(uint64, tag = "7")]
    pub merge_at: u64,
}
/// zmessage type = Z_TYPE_CLOCK
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZClock {
    #[prost(enumeration = "ClockType", tag = "1")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Server Clock Message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventTrigger {
    #[prost(message, optional, tag = "1")]
    pub clock_info: ::core::option::Option<ClockInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiffReq {
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub from_clock: ::core::option::Option<ClockInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiffRsp {
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "2")]
    pub diffs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub from: ::core::option::Option<ClockInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveSync {
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "2")]
    pub diffs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub latest: ::core::option::Option<ClockInfo>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClockType {
    TypeEventTrigger = 0,
    TypeDiffReq = 1,
    TypeDiffRsp = 2,
    TypeActiveSync = 3,
}
impl ClockType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ClockType::TypeEventTrigger => "TYPE_EVENT_TRIGGER",
            ClockType::TypeDiffReq => "TYPE_DIFF_REQ",
            ClockType::TypeDiffRsp => "TYPE_DIFF_RSP",
            ClockType::TypeActiveSync => "TYPE_ACTIVE_SYNC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TYPE_EVENT_TRIGGER" => Some(Self::TypeEventTrigger),
            "TYPE_DIFF_REQ" => Some(Self::TypeDiffReq),
            "TYPE_DIFF_RSP" => Some(Self::TypeDiffRsp),
            "TYPE_ACTIVE_SYNC" => Some(Self::TypeActiveSync),
            _ => None,
        }
    }
}
