// This file is @generated by prost-build.
/// Zp2p
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Zp2p {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// for p2p
    #[prost(enumeration = "ZIndentity", tag = "2")]
    pub r#type: i32,
    /// for p2p
    #[prost(enumeration = "ZAction", tag = "3")]
    pub action: i32,
    /// for vlc
    #[prost(enumeration = "ZPushType", tag = "4")]
    pub push_type: i32,
    #[prost(message, optional, tag = "5")]
    pub message: ::core::option::Option<super::zmessage::ZMessage>,
    #[prost(bytes = "vec", tag = "6")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// for verifying
    #[prost(bytes = "vec", tag = "7")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ZIndentity {
    /// client
    UTypeCli = 0,
    /// server
    UTypeSer = 1,
}
impl ZIndentity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ZIndentity::UTypeCli => "U_TYPE_CLI",
            ZIndentity::UTypeSer => "U_TYPE_SER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "U_TYPE_CLI" => Some(Self::UTypeCli),
            "U_TYPE_SER" => Some(Self::UTypeSer),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ZAction {
    /// read
    ZTypeRead = 0,
    /// write
    ZTypeWrite = 1,
}
impl ZAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ZAction::ZTypeRead => "Z_TYPE_READ",
            ZAction::ZTypeWrite => "Z_TYPE_WRITE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Z_TYPE_READ" => Some(Self::ZTypeRead),
            "Z_TYPE_WRITE" => Some(Self::ZTypeWrite),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ZPushType {
    /// direct msg
    ZTypeDm = 0,
    /// broadcast
    ZTypeBc = 1,
}
impl ZPushType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ZPushType::ZTypeDm => "Z_TYPE_DM",
            ZPushType::ZTypeBc => "Z_TYPE_BC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Z_TYPE_DM" => Some(Self::ZTypeDm),
            "Z_TYPE_BC" => Some(Self::ZTypeBc),
            _ => None,
        }
    }
}
