//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "merge_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_id: String,
    pub to_id: String,
    pub start_count: i32,
    pub end_count: i32,
    pub s_clock_hash: String,
    pub e_clock_hash: String,
    pub merge_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clock_infos::Entity",
        from = "Column::EClockHash",
        to = "super::clock_infos::Column::ClockHash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClockInfos2,
    #[sea_orm(
        belongs_to = "super::clock_infos::Entity",
        from = "Column::SClockHash",
        to = "super::clock_infos::Column::ClockHash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClockInfos1,
}

impl ActiveModelBehavior for ActiveModel {}
