//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::bussiness_clocks::Entity as BussinessClocks;
pub use super::clock_infos::Entity as ClockInfos;
pub use super::merge_logs::Entity as MergeLogs;
pub use super::z_messages::Entity as ZMessages;
